# Generated by Django 5.0.7 on 2024-08-05 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('plate_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='车牌号')),
                ('passenger_capacity', models.IntegerField(verbose_name='载客量')),
            ],
            options={
                'db_table': 'bus',
            },
        ),
        migrations.CreateModel(
            name='Contain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'contain',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='司机工号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=3, verbose_name='性别')),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='DriverTelephone',
            fields=[
                ('telephone', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='电话号码')),
            ],
            options={
                'db_table': 'driver_telephone',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='线路编号')),
            ],
            options={
                'db_table': 'line',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='管理员工号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=3, verbose_name='性别')),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='ManagerTelephone',
            fields=[
                ('telephone', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='电话号码')),
            ],
            options={
                'db_table': 'manager_telephone',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('telephone', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='电话号码')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=3, verbose_name='密码')),
            ],
            options={
                'db_table': 'passenger',
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_time', models.DateTimeField(verbose_name='乘坐时间')),
            ],
            options={
                'db_table': 'ride',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='站点编号')),
                ('name', models.CharField(max_length=20, verbose_name='站点名称')),
            ],
            options={
                'db_table': 'site',
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='值班开始时间')),
                ('end_time', models.DateTimeField(verbose_name='值班结束时间')),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.bus', verbose_name='车牌号')),
            ],
            options={
                'db_table': 'drive',
            },
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.CheckConstraint(check=models.Q(('sex', '男'), ('sex', '女'), _connector='OR'), name='driver_check_sex_value'),
        ),
        migrations.AddField(
            model_name='drive',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.driver', verbose_name='司机工号'),
        ),
        migrations.AddField(
            model_name='drivertelephone',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.driver', verbose_name='司机工号'),
        ),
        migrations.AddField(
            model_name='contain',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.line', verbose_name='线路编号'),
        ),
        migrations.AddField(
            model_name='bus',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.line', verbose_name='所属线路'),
        ),
        migrations.AddConstraint(
            model_name='manager',
            constraint=models.CheckConstraint(check=models.Q(('sex', '男'), ('sex', '女'), _connector='OR'), name='manager_check_sex_value'),
        ),
        migrations.AddField(
            model_name='managertelephone',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.manager', verbose_name='管理人员工号'),
        ),
        migrations.AddConstraint(
            model_name='passenger',
            constraint=models.CheckConstraint(check=models.Q(('sex', '男'), ('sex', '女'), _connector='OR'), name='passenger_check_sex_value'),
        ),
        migrations.AddField(
            model_name='ride',
            name='passenger_tel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.passenger', verbose_name='电话号码'),
        ),
        migrations.AddField(
            model_name='ride',
            name='plate_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.bus', verbose_name='车牌号'),
        ),
        migrations.AddField(
            model_name='contain',
            name='last_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_site', to='system.site', verbose_name='上一站点编号'),
        ),
        migrations.AddField(
            model_name='contain',
            name='next_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_site', to='system.site', verbose_name='下一站点编号'),
        ),
        migrations.AddField(
            model_name='contain',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='system.site', verbose_name='站点编号'),
        ),
        migrations.AlterUniqueTogether(
            name='drive',
            unique_together={('plate_number', 'driver', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='ride',
            unique_together={('plate_number', 'passenger_tel', 'travel_time')},
        ),
        migrations.AlterUniqueTogether(
            name='contain',
            unique_together={('site', 'line')},
        ),
    ]
