# Generated by Django 5.0.7 on 2024-08-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='站点名称'),
        ),
    ]
