# Generated by Django 5.0.7 on 2024-08-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='线路编号'),
        ),
    ]
