# Generated by Django 5.0.7 on 2024-08-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_lineview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverView',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=3)),
                ('telephone', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'driver_view',
                'managed': False,
            },
        ),
    ]
