# Generated by Django 5.0.7 on 2024-08-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_driverview'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('driver_id', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=20)),
                ('plate_number_id', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'driver_view',
                'managed': False,
            },
        ),
    ]
