# Generated by Django 5.0.7 on 2024-08-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_workview'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workview',
            table='work_view',
        ),
    ]
