# Generated by Django 5.0.7 on 2024-08-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_workview_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=10)),
                ('line_id', models.IntegerField()),
                ('passenger_tel_id', models.CharField(max_length=11)),
                ('travel_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'ride_view',
                'managed': False,
            },
        ),
    ]
