# Generated by Django 5.0.7 on 2024-08-12 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_rideview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='公告编号')),
                ('title', models.CharField(max_length=90, verbose_name='公告标题')),
                ('text', models.TextField(verbose_name='公告内容')),
                ('date', models.DateField(verbose_name='发布日期')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.manager', verbose_name='发布者')),
            ],
            options={
                'db_table': 'announcement',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='违章编号')),
                ('title', models.CharField(max_length=90, verbose_name='违章标题')),
                ('text', models.TextField(verbose_name='违章内容')),
                ('status', models.IntegerField(choices=[(0, '未处理'), (1, '已通过'), (2, '未通过')], default=0, verbose_name='处理状态')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.manager', verbose_name='处理人员')),
            ],
            options={
                'db_table': 'violation',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.driver', verbose_name='被投诉司机工号')),
                ('passenger_tel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.passenger', verbose_name='投诉人电话')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.violation', verbose_name='违章编号')),
            ],
            options={
                'db_table': 'complaint',
                'unique_together': {('driver', 'passenger_tel', 'violation')},
            },
        ),
    ]
