# Generated by Django 5.0.7 on 2024-08-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_announcementview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drive',
            unique_together={('plate_number', 'start_time')},
        ),
    ]
