# Generated by Django 5.0.7 on 2024-08-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_alter_drive_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='complaint',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='passenger_tel',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='violation',
        ),
        migrations.RemoveField(
            model_name='violation',
            name='manager',
        ),
        migrations.DeleteModel(
            name='ViolationView',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Violation',
        ),
    ]
