# Generated by Django 5.0.7 on 2024-08-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_violation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=90)),
                ('text', models.TextField()),
                ('status', models.IntegerField()),
                ('manager_id', models.CharField(max_length=6)),
                ('passenger_tel_id', models.CharField(max_length=11)),
                ('driver_id', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'violation_view',
                'managed': False,
            },
        ),
    ]
